[package]
name = "rust_webgl_example"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "console",
    "Window",
    "Document",
    "Element",
    "Animation",
    "HtmlCanvasElement",
    "WebGlRenderingContext",
    "WebGlBuffer",
    "WebGlProgram", 
    "WebGlShader",
    "WebGlUniformLocation",
    "MouseEvent",
    "KeyboardEvent",
    
    "AddEventListenerOptions"
] }
js-sys = "0.3"

[lib]
crate-type = ["cdylib"]